### ISSUE TITLE
leaveCommunity() should be internal

### ISSUE THREAD

**Issue by auryn-macmillan** [EBOGDAO/og-dapp#11]
https://github.com/EBOGDAO/og-dapp/blob/0a2e2ecfae21dc4677f6c4cc6a17992286c2f362/contracts/Agreement.sol#L104-L106

When would a user call this function?
It seems like it should only be called by the `optOutOfDAO()` function, in which case it should be internal.
That being the case, it probably makes more sense to just move `renounceRole("OG", msg.sender);` to the end of the `optOutOfDAO()` function.

**Comment by stinkyfi** [comment]
Resolved in PR #12 
Won't close until merged
Tested on Rinkeby: 0x0dA13640D88754E52Fdd5163D5383b6f5cFD31FA
