### ISSUE TITLE
Virtual functions?

### ISSUE THREAD

**Issue by auryn-macmillan** [EBOGDAO/og-dapp#8]
Why are all of these functions marked as virtual?
I can't imagine any reason that they would be imported into another contract, so no need to mark them as virtual.

https://github.com/EBOGDAO/og-dapp/blob/0a2e2ecfae21dc4677f6c4cc6a17992286c2f362/contracts/Agreement.sol#L74-L111

**Comment by stinkyfi** [comment]
Issue is addressed PR: https://github.com/EBOGDAO/og-dapp/pull/12
Won't close until merged
