### ISSUE TITLE
Use onlyRole instead of only member

### ISSUE THREAD

**Issue by auryn-macmillan** [EBOGDAO/og-dapp#9]
https://github.com/EBOGDAO/og-dapp/blob/0a2e2ecfae21dc4677f6c4cc6a17992286c2f362/contracts/Agreement.sol#L43-L46

You should use the onlyRole() modifier from OZ access control, rather than implementing your own onlyMember() modifier.

Use `onlyRole("OG")` anywhere that you have used `onlyMember()`.

**Comment by stinkyfi** [comment]
Issue is addressed in PR: https://github.com/EBOGDAO/og-dapp/pull/12
Tested on Rinkeby:
0xab5cAA579410Dd0eCfbB7dd11759350BE2d01A93

won't close until merged
